# Built with Jekyll 3.2.0

# Setup
title:               Graduate Descent
tagline:             'Stochastic thoughts on technology, society, and academia.'
description:         'GraduateDescent is a blog written by two Ph.D. students in Robotics and Artificial Intelligence.'
url:                 'http://www.graduatedescent.com'
baseurl:             ''

# About/contact
author:
  name:              Valentin Peretroukhin
  url:               https://twitter.com/valentinp
  email:             valentinp@gmail.com

# Permalinks

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme: 

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor


